export enum NotificationType {
  // Orders
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_FAILED = 'ORDER_FAILED',
  ORDER_PAID = 'ORDER_PAID',
  ORDER_CANCELED = 'ORDER_CANCELED',

  // Payments
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',

  // General
  SYSTEM_ERROR = 'SYSTEM_ERROR',
}